# Generated by Django 5.0.6 on 2024-05-31 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_API', '0002_alter_coach_user_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_1_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_2_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_count',
        ),
        migrations.RemoveField(
            model_name='team',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_games', to='NBA_API.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_games', to='NBA_API.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_games', to='NBA_API.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='NBA_API.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBA_API.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='NBA_API.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
