# Generated by Django 5.0.6 on 2024-05-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_API', '0003_alter_team_coach_remove_game_team_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
